import type { CapabilityId } from './capabilities';

export type Modality = 'text' | 'image' | 'audio' | 'embed';

export interface Model {
  id: string;
  name: string;
  provider: string;
  caps: CapabilityId[];
  free: boolean;
  tool: boolean;
  q: number;      // quality 0–10
  lat: number;    // latency ms
  cost: number;   // USD per 1M tokens (0 = free)
  ctx: number;    // context window, thousands of tokens (0 = n/a)
  mod: Modality;
  priv: number;   // privacy 0–10
  avail: number;  // availability 0–10
}

const m = (id: string, name: string, provider: string, caps: CapabilityId[], o: Partial<Model> = {}): Model => ({
  id, name, provider, caps,
  q: 6, lat: 600, cost: 1.5, ctx: 128, mod: 'text', priv: 5, avail: 9,
  ...o,
  free: o.free ?? false,
  tool: o.tool ?? false,
});

// Representative seed (~20). The full deterministic 400-model catalog lives in
// ../artweb-studio/models.seed.json (generated by generate_models.py).
export const MODELS: Model[] = [
  m('gpt-4o-mini', 'GPT-4o mini', 'OpenAI', ['tool_use', 'vision', 'web', 'reasoning', 'safety'], { free: true, q: 7, lat: 700, cost: 0.15, ctx: 128 }),
  m('claude-haiku', 'Claude 3.5 Haiku', 'Anthropic', ['tool_use', 'vision', 'safety'], { q: 7, lat: 600, cost: 0.8, ctx: 200 }),
  m('gemini-flash', 'Gemini 1.5 Flash', 'Google', ['tool_use', 'vision', 'audio', 'web', 'free'], { free: true, q: 7, lat: 400, cost: 0.075, ctx: 1000 }),
  m('gemini-pro', 'Gemini 1.5 Pro', 'Google', ['tool_use', 'vision', 'audio', 'web'], { q: 8, lat: 900, cost: 1.25, ctx: 2000 }),
  m('llama-3.1-70b', 'Llama 3.1 70B', 'Meta', ['tool_use', 'reasoning'], { q: 8, lat: 800, cost: 0.6, ctx: 128 }),
  m('llama-3.1-8b', 'Llama 3.1 8B', 'Meta', ['tool_use', 'free'], { free: true, q: 6, lat: 250, cost: 0, ctx: 128 }),
  m('deepseek-chat', 'DeepSeek-V3', 'DeepSeek', ['tool_use', 'code', 'reasoning'], { q: 9, lat: 900, cost: 0.27, ctx: 64 }),
  m('deepseek-r1', 'DeepSeek-R1', 'DeepSeek', ['reasoning', 'code'], { q: 9, lat: 1200, cost: 0.55, ctx: 64 }),
  m('qwen2.5-72b', 'Qwen2.5 72B', 'Alibaba', ['tool_use', 'code'], { q: 8, lat: 700, cost: 0.4, ctx: 128 }),
  m('qwen2.5-7b', 'Qwen2.5 7B', 'Alibaba', ['tool_use', 'free'], { free: true, q: 5, lat: 200, cost: 0, ctx: 128 }),
  m('mixtral-8x7b', 'Mixtral 8x7B', 'Mistral', ['tool_use', 'free'], { free: true, q: 6, lat: 450, cost: 0, ctx: 32 }),
  m('mistral-large', 'Mistral Large', 'Mistral', ['tool_use', 'code'], { q: 8, lat: 700, cost: 2, ctx: 128 }),
  m('groq-llama', 'Llama 3.3 70B', 'Groq', ['tool_use', 'speed'], { q: 7, lat: 120, cost: 0.59, ctx: 128 }),
  m('groq-mixtral', 'Mixtral 8x7B', 'Groq', ['tool_use', 'speed', 'free'], { free: true, q: 6, lat: 90, cost: 0, ctx: 32 }),
  m('codestral', 'Codestral', 'Mistral', ['code', 'tool_use'], { q: 8, lat: 500, cost: 0.2, ctx: 32 }),
  m('o1-mini', 'o1-mini', 'OpenAI', ['reasoning', 'code'], { q: 9, lat: 1500, cost: 3, ctx: 128 }),
  m('claude-opus', 'Claude 3.5 Opus', 'Anthropic', ['tool_use', 'vision', 'reasoning', 'safety'], { q: 10, lat: 1200, cost: 15, ctx: 200 }),
  m('whisper-large', 'Whisper Large', 'OpenAI', ['audio', 'free'], { free: true, q: 7, lat: 900, cost: 0, ctx: 0, mod: 'audio' }),
  m('sdxl', 'SDXL', 'Stability', ['vision', 'free'], { free: true, q: 7, lat: 2000, cost: 0, ctx: 0, mod: 'image' }),
  m('phi-3.5', 'Phi-3.5', 'Microsoft', ['free', 'reasoning'], { free: true, q: 5, lat: 180, cost: 0, ctx: 128 }),
  m('gemma-2-9b', 'Gemma 2 9B', 'Google', ['tool_use', 'free'], { free: true, q: 6, lat: 220, cost: 0, ctx: 8 }),
  m('command-r', 'Command R+', 'Cohere', ['tool_use', 'web'], { q: 7, lat: 800, cost: 0.15, ctx: 128 }),
];
